### ISSUE TITLE
Why Tcl?

### ISSUE THREAD

**Issue by nikolay** [efrecon/machinery#1]
I see it's a dear language to you, but don't you agree this will prevent getting more contributors on board?

**Comment by efrecon** [comment]
Probably, but this is the language that I am most fluent with. `machinery` came out of my needs and pushing it out is a way to perhaps attract contributors, but at least a way to attract beta testers. I am publishing binaries for that very purpose and can probably publish for more platforms if there is a need.

Tcl isn't so hard, maybe would this be the opportunity to learn?

**Comment by nikolay** [comment]
@efrecon Makes sense. I will definitely look into it. :smile:
