### ISSUE TITLE
OS X no longer supported

### ISSUE THREAD

**Issue by nikolay** [efrecon/machinery#4]
Latest versions require Tcl 8.6 and the latest OS X ships with 8.5.9.

**Comment by nikolay** [comment]
You can do the following with Homebrew though:

``` bash
$ brew tap homebrew/dupes
$ brew update
$ brew install tcl-tk
$ alias machinery="$(brew --prefix tcl-tk)/bin/tclsh $(brew --prefix)/opt/machinery/machinery"
```

**Comment by efrecon** [comment]
Which Mac OSX version are you running on? A friend of mine has 10.9 and the latest installed Tcl is 8.6 on his machine.

**Comment by nikolay** [comment]
I am on OS X 10.10, the latest.

``` bash
$ echo 'puts [info patchlevel];' | tclsh
8.5.9
```

**Comment by nikolay** [comment]
The Homebrew version:

``` bash
$ echo 'puts [info patchlevel];' | $(brew --prefix tcl-tk)/bin/tclsh
8.6.4
```

**Comment by efrecon** [comment]
I have recoded how external program are run under the control of machinery and the new code require features that appeared in 8.6. The old code is actually still there, I'll see if I can revive it and dynamically switch depending on the Tcl version. I am also looking into making binaries for OSX, to make it simpler for people to try it out.

**Comment by efrecon** [comment]
@nikolay , I wonder if you could try this [OSX binary](https://drive.google.com/file/d/0Bz65kSKRQe3jT09IdTdjcWtoTHc/view?usp=sharing) and see if that works for you? It is my current dev. release, soon to be 0.5.1 and I'd like to see if I can start pushing out OSX binaries as part of the coming releases.

**Comment by nikolay** [comment]
@efrecon Sorry, didn't get a chance to see this earlier. I will test it right now, thanks!

**Comment by efrecon** [comment]
@nikolay The OSX binary that I posted above did not work properly. Try [this one](https://drive.google.com/open?id=0Bz65kSKRQe3jUFhHMjFjUUx0aEk&authuser=0) instead.  I have managed to test it on one machine, but am eager to see if it solves your problems.

**Comment by efrecon** [comment]
I am closing this, `machinery` now explicitly requires Tcl 8.6. Binaries for OSX are now provided for people that just want to try.
