### ISSUE TITLE
Variable name mix-up in cluster.tcl? 

### ISSUE THREAD

**Issue by wallb** [efrecon/machinery#47]
Looks like there is a mix of "environement" and "environment" in lib/cluster/cluster.tcl, e.g. at:
https://github.com/efrecon/machinery/blob/e7d5c92207a0b4fceaec8ef3f8039867aa2a3652/lib/cluster/cluster.tcl#L754

**Comment by efrecon** [comment]
Fixed `environement` does not appear anymore in `lib/cluster/cluster.tcl`
