### ISSUE TITLE
machopts in cluster.tcl

### ISSUE THREAD

**Issue by wallb** [efrecon/machinery#48]
Looks like machopts is a list...

https://github.com/efrecon/machinery/blob/e7d5c92207a0b4fceaec8ef3f8039867aa2a3652/lib/cluster/cluster.tcl#L2347

https://github.com/efrecon/machinery/blob/e7d5c92207a0b4fceaec8ef3f8039867aa2a3652/lib/cluster/cluster.tcl#L2350

**Comment by efrecon** [comment]
Fixed
